service: aws-serverless-hotel-api
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:AWS_PROFILE}
  region: eu-north-1
  iam:
    role: ${env:AWS_IAM_ROLE}
  environment:
    DYNAMO_DB_TABLE: ${env:DYNAMO_DB_TABLE}
    GSI_ROOM_BY_ROOM_SIZE:  ${env:GSI_ROOM_BY_ROOM_SIZE}
    GSI_GENERIC_PK_SK: ${env:GSI_GENERIC_PK_SK}
    #GSI_GENERIC_PK_SK="GSI_GENERIC_PK_SK"
    
plugins:
  - serverless-webpack
  - serverless-scriptable-plugin

package: 
  individually: true

custom:
  scriptable:
    hooks:
      #after:aws:deploy:deploy:createStack:  generate_booking.js
      #after:aws:deploy:deploy:createStack:  generate_hotel_rooms.js

functions:
  bookRoom:
    handler: functions/bookRoom/index.handler
    events:
      - httpApi:
          path: '/book'
          method: POST
  queryRooms:
    handler:  functions/get/availableRooms/index.handler
    events:
      - httpApi:
          path: '/rooms'
          method: GET
  currentBookings:
    handler:  functions/get/currentBookings/index.handler
    events:
      - httpApi:
          path: '/bookings/current'
          method: GET
  deleteBooking:
    handler: functions/delete/index.handler 
    events:
      - httpApi:
          path: '/bookings/{id}'
          method: DELETE
          

resources:
 Resources:
    teamDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hotel-db # Database table name
        AttributeDefinitions:
          - AttributeName: id # database item id
            AttributeType: S # String
          - AttributeName: roomSize 
            AttributeType: N
          - AttributeName: GSI_PK_1 
            AttributeType: S
          - AttributeName: GSI_SK_1 
            AttributeType: S
        KeySchema:
          - AttributeName: id # database key id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: "GSI_HOTEL_ONE"
            KeySchema:
            - AttributeName: roomSize
              KeyType: "HASH"
            Projection:
              ProjectionType: ALL
          - IndexName: "GSI_GENERIC_PK_SK"
            KeySchema: 
            - AttributeName: GSI_PK_1
              KeyType: HASH
            - AttributeName: GSI_SK_1
              KeyType: RANGE
            Projection:
                ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST