service: aws-serverless-hotel-api
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:AWS_PROFILE}
  region: eu-north-1
  iam:
    role: ${env:AWS_IAM_ROLE}
  environment:
    DYNAMO_DB_TABLE: ${env:DYNAMO_DB_TABLE}
    
plugins:
  - serverless-webpack
  - serverless-scriptable-plugin

package: 
  individually: true


# UNCOMMENT generate INSIDE generate_hotel_rooms.js TO POPULATE TABLE 
custom:
  scriptable:
    hooks:
      after:aws:deploy:deploy:createStack:  generate_hotel_rooms.js

functions:
  function1:
    handler: index.handler
  queryRooms:
    handler:  functions/get/availableRooms/index.handler
    events:
      - httpApi:
          path: '/rooms'
          method: GET

resources:
  Resources:
    teamDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hotel-db # Database table name
        AttributeDefinitions:
          - AttributeName: id # database item id
            AttributeType: S # String
        KeySchema:
          - AttributeName: id # database key id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST